### ISSUE TITLE
memory leak in tnt_reply_free

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool-c#20]
tnt_reply_free doesn't free reply if it was alloced

**Comment by danikin** [comment]
I'm using tnt_reply from another thread than tnt_flush and having the following issue.

This way it leaks

while (1)
{
struct tnt_reply * reply = tnt_reply_init(NULL);
tnt->read_reply(tnt, reply);
tnt_reply_free(reply);
}

This way it crashes (double frees)

while (1)
{
struct tnt_reply reply;
tnt_reply_init(&reply);
tnt->read_reply(tnt, &reply);
tnt_reply_free(&reply);
}

And this way it also crashes

struct tnt_reply reply;
tnt_reply_init(&reply);

while (1)
{
tnt->read_reply(tnt, &reply);
tnt_reply_free(&reply);
}

All I need it just a way to read all the answers from a Tarantool server as long as I want it in a separate thread. Plus, I don't want to pay extra money for inter thread sync, so if it's possible then decouple please write and read buffers in order to do write & read in parallel with no extra cost.
